### ISSUE TITLE
[Polygon] single user balancer resolver (Gelato)

### ISSUE THREAD

**Issue by 0xtuytuy** [GetAlluo/alluo-protocol#47]
### Summary

1. Name: [Polygon] single user balancer resolver (Gelato)
2. About: Build a resolver that will emit the balance of the user on a daily basis.

### Is your proposal related to a problem?

No problem, just improvement

### Describe the solution you'd like

_WIP_

There is no way to know today what the user's balance was yesterday or a few weeks ago. This is very useful metadata for analytics purposes.

### Additional context

This resolver event will be used by the mobile app but also by the BE to create analytics allows the core team and the community to analyse growth and give feedback to the users on their gains.

**Comment by alexanderem49** [comment]
@0-xec did this via dune

**Comment by alexanderem49** [comment]
@0-xec did it via Dune
